POST http://localhost:3000/register
Content-Type: application/json

{
    "name" : "Vitalie",
    "email" : "vitallie@admin.111",
    "password" : "password"
}

###
GET http://localhost:3000/

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "vitalie@admin.111",
    "password" : "password"
}

###
GET http://localhost:3000/quiz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2ZmVkNTRmM2FjYzQ2NDFlZjEyYzYiLCJuYW1lIjoiVml0YWxpZSIsImVtYWlsIjoidml0YWxpZUBhZG1pbi4xMTEiLCJwYXNzd29yZCI6IiQyYiQxMCRFZ0FRcm51UlNlMkRhR0NEZ2FmdUdlbi5DUXhNVDRac3MzNlFwVGdEbUpYcnRNeDFVbHVmLiIsImNyZWF0ZWRBdCI6IjIwMjQtMDUtMTdUMDY6NTM6MDkuMTY2WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDUtMTdUMDY6NTM6MDkuMTY2WiIsIl9fdiI6MCwiaWF0IjoxNzE2NDczMzA0LCJleHAiOjE3MTY0NzY5MDR9.w998Oi_i74QnOf9XLocJqSTuxerwqDHuLiOzzKxOEvg

