GET http://localhost:3000/quizAttempt

###

POST http://localhost:3000/question
Content-Type: application/json

{
    "updatedSkillLevel" : "3"
}

###

POST http://localhost:3000/answer
Content-Type: application/json

{
    "answerNumber" : "1",
    "updatedSkillLevel" : "1"
}